[package]
name = "notification"
version = "0.1.0"
authors = ["u0_a285"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
regex = "1"
mqtt-protocol = "0.11"